import {
  Download,
  Pen,
  Layers,
  Image,
  ShieldCheck,
  Music,
  Clapperboard,
} from "lucide-react";
import { PipelineStage } from "@contenthq/shared";
import type { ConsolidatedStage } from "./types";

export const CONSOLIDATED_STAGES: ConsolidatedStage[] = [
  {
    id: "ingestion",
    label: "Ingestion",
    tagline: "Fetching raw content",
    icon: Download,
    color: "#06B6D4",
    colorEnd: "#0891B2",
    rawStages: [PipelineStage.INGESTION],
    primaryStage: PipelineStage.INGESTION,
  },
  {
    id: "story-writing",
    label: "Story Writing",
    tagline: "Crafting the narrative",
    icon: Pen,
    color: "#8B5CF6",
    colorEnd: "#7C3AED",
    rawStages: [PipelineStage.STORY_WRITING],
    primaryStage: PipelineStage.STORY_WRITING,
  },
  {
    id: "scene-generation",
    label: "Scene Gen",
    tagline: "Breaking into scenes",
    icon: Layers,
    color: "#3B82F6",
    colorEnd: "#2563EB",
    rawStages: [PipelineStage.SCENE_GENERATION],
    primaryStage: PipelineStage.SCENE_GENERATION,
  },
  {
    id: "visual-generation",
    label: "Visual Gen",
    tagline: "Creating visuals & video",
    icon: Image,
    color: "#6366F1",
    colorEnd: "#4F46E5",
    rawStages: [PipelineStage.VISUAL_GENERATION, PipelineStage.VIDEO_GENERATION],
    primaryStage: PipelineStage.VISUAL_GENERATION,
  },
  {
    id: "visual-verification",
    label: "Verification",
    tagline: "Quality assurance",
    icon: ShieldCheck,
    color: "#10B981",
    colorEnd: "#059669",
    rawStages: [PipelineStage.VISUAL_VERIFICATION],
    primaryStage: PipelineStage.VISUAL_VERIFICATION,
  },
  {
    id: "audio-layering",
    label: "Audio",
    tagline: "Voice & music mixing",
    icon: Music,
    color: "#F59E0B",
    colorEnd: "#D97706",
    rawStages: [PipelineStage.TTS_GENERATION, PipelineStage.AUDIO_MIXING],
    primaryStage: PipelineStage.TTS_GENERATION,
  },
  {
    id: "assembly",
    label: "Assembly",
    tagline: "Final video render",
    icon: Clapperboard,
    color: "#EC4899",
    colorEnd: "#DB2777",
    rawStages: [PipelineStage.VIDEO_ASSEMBLY],
    primaryStage: PipelineStage.VIDEO_ASSEMBLY,
  },
];
