import type { PipelineTemplate } from "../types/pipeline-template";

/**
 * Built-in AI Video pipeline template.
 * Mirrors the current 10-stage pipeline exactly for backward compatibility.
 */
export const AI_VIDEO_TEMPLATE: PipelineTemplate = {
  id: "builtin-ai-video",
  name: "AI Video",
  slug: "ai-video",
  description:
    "Full AI-powered video pipeline: ingest content, generate story, create visuals, add voiceover, and assemble final video.",
  version: 1,
  outputType: "ai_video",
  isBuiltIn: true,
  createdBy: null,
  defaultConfig: {},
  stages: [
    {
      stageId: "ingestion",
      label: "Content Ingestion",
      queueName: "ingestion",
      jobName: "ingest",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "ingestion",
      progressPercent: 0,
      projectStatus: "ingesting",
      dependsOn: [],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "story-writing",
      label: "Story Writing",
      queueName: "story-writing",
      jobName: "write-story",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "storyWriting",
      progressPercent: 10,
      projectStatus: "writing",
      dependsOn: ["ingestion"],
      queueConfig: {
        concurrency: 3,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "scene-generation",
      label: "Scene Generation",
      queueName: "scene-generation",
      jobName: "generate-scenes",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "sceneGeneration",
      progressPercent: 20,
      projectStatus: "generating_scenes",
      dependsOn: ["story-writing"],
      queueConfig: {
        concurrency: 10,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "visual-generation",
      label: "Visual Generation",
      queueName: "visual-generation",
      jobName: "generate-visual",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "visualGeneration",
      progressPercent: 30,
      projectStatus: "generating_visuals",
      sceneStatusOnComplete: "visual_generated",
      dependsOn: ["scene-generation"],
      queueConfig: {
        concurrency: 5,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "visual-verification",
      label: "Visual Verification",
      queueName: "visual-verification",
      jobName: "verify-visual",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: true,
      configKey: "visualVerification",
      progressPercent: 40,
      projectStatus: "verifying",
      sceneStatusOnComplete: "visual_verified",
      dependsOn: ["visual-generation"],
      queueConfig: {
        concurrency: 10,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "tts-generation",
      label: "Voice Generation",
      queueName: "tts-generation",
      jobName: "generate-tts",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "tts",
      progressPercent: 50,
      projectStatus: "generating_tts",
      dependsOn: ["visual-verification"],
      queueConfig: {
        concurrency: 5,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "audio-mixing",
      label: "Audio Mixing",
      queueName: "audio-mixing",
      jobName: "mix-audio",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "audioMixing",
      progressPercent: 60,
      projectStatus: "mixing_audio",
      sceneStatusOnComplete: "audio_mixed",
      dependsOn: ["tts-generation"],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "video-generation",
      label: "Video Generation",
      queueName: "video-generation",
      jobName: "generate-video",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: true,
      configKey: "videoGeneration",
      progressPercent: 70,
      projectStatus: "generating_video",
      sceneStatusOnComplete: "video_generated",
      dependsOn: ["audio-mixing"],
      queueConfig: {
        concurrency: 3,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "ffmpeg",
    },
    {
      stageId: "caption-generation",
      label: "Caption Generation",
      queueName: "caption-generation",
      jobName: "generate-caption",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: true,
      configKey: "captionGeneration",
      progressPercent: 80,
      projectStatus: "generating_captions",
      sceneStatusOnComplete: "caption_generated",
      dependsOn: ["audio-mixing"],
      queueConfig: {
        concurrency: 5,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 1000,
      },
    },
    {
      stageId: "video-assembly",
      label: "Final Assembly",
      queueName: "video-assembly",
      jobName: "assemble-video",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "assembly",
      progressPercent: 90,
      projectStatus: "assembling",
      dependsOn: ["video-generation", "caption-generation"],
      queueConfig: {
        concurrency: 2,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "ffmpeg",
    },
  ],
};
