import type { PipelineTemplate } from "../types/pipeline-template";

/**
 * Built-in Motion Canvas pipeline template.
 * Creates animated videos using Motion Canvas imperative animation API.
 */
export const MOTION_CANVAS_TEMPLATE: PipelineTemplate = {
  id: "builtin-motion-canvas",
  name: "Motion Canvas Video",
  slug: "motion-canvas",
  description:
    "Create animated videos with Motion Canvas. AI generates content and animation specs, Motion Canvas renders professional animations.",
  version: 1,
  outputType: "motion_canvas_video",
  isBuiltIn: true,
  createdBy: null,
  defaultConfig: {},
  stages: [
    {
      stageId: "ingestion",
      label: "Content Ingestion",
      queueName: "ingestion",
      jobName: "ingest",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "ingestion",
      progressPercent: 0,
      projectStatus: "ingesting",
      dependsOn: [],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "story-writing",
      label: "Story Writing",
      queueName: "story-writing",
      jobName: "write-story",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "storyWriting",
      progressPercent: 15,
      projectStatus: "writing",
      dependsOn: ["ingestion"],
      queueConfig: {
        concurrency: 3,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "scene-generation",
      label: "Scene Generation",
      queueName: "scene-generation",
      jobName: "generate-scenes",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "sceneGeneration",
      progressPercent: 30,
      projectStatus: "generating_scenes",
      dependsOn: ["story-writing"],
      queueConfig: {
        concurrency: 10,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "motion-canvas-scene",
      label: "Motion Canvas Scene",
      queueName: "motion-canvas-scene",
      jobName: "create-mc-scene",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "motionCanvasScene",
      progressPercent: 50,
      projectStatus: "generating_visuals",
      dependsOn: ["scene-generation"],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "motion-canvas",
    },
    {
      stageId: "motion-canvas-render",
      label: "Motion Canvas Render",
      queueName: "motion-canvas-render",
      jobName: "render-mc",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "motionCanvasRender",
      progressPercent: 75,
      projectStatus: "assembling",
      dependsOn: ["motion-canvas-scene"],
      queueConfig: {
        concurrency: 2,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 10000,
      },
      renderingBackend: "motion-canvas",
    },
  ],
};
