import type { PipelineTemplate } from "../types/pipeline-template";

/**
 * Built-in Presentation pipeline template.
 * Converts presentations (PPTX/PDF/Google Slides) into narrated videos.
 * Based on the ppt_app pipeline pattern.
 */
export const PRESENTATION_TEMPLATE: PipelineTemplate = {
  id: "builtin-presentation",
  name: "Presentation Video",
  slug: "presentation",
  description:
    "Transform presentations into narrated videos with AI-generated scripts, TTS voiceover, and professional assembly.",
  version: 1,
  outputType: "presentation",
  isBuiltIn: true,
  createdBy: null,
  defaultConfig: {},
  stages: [
    {
      stageId: "ppt-ingestion",
      label: "Presentation Ingestion",
      queueName: "ppt-ingestion",
      jobName: "ingest-ppt",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "pptIngestion",
      progressPercent: 0,
      projectStatus: "ingesting",
      dependsOn: [],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "slide-rendering",
      label: "Slide Rendering",
      queueName: "slide-rendering",
      jobName: "render-slide",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "slideRendering",
      progressPercent: 20,
      projectStatus: "generating_visuals",
      dependsOn: ["ppt-ingestion"],
      queueConfig: {
        concurrency: 10,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "slidev",
    },
    {
      stageId: "audio-script-gen",
      label: "Narration Script Generation",
      queueName: "audio-script-gen",
      jobName: "generate-audio-script",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "audioScriptGen",
      progressPercent: 40,
      projectStatus: "writing",
      dependsOn: ["ppt-ingestion"],
      queueConfig: {
        concurrency: 3,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "tts-generation",
      label: "Voice Generation",
      queueName: "tts-generation",
      jobName: "generate-tts",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "tts",
      progressPercent: 55,
      projectStatus: "generating_tts",
      dependsOn: ["audio-script-gen"],
      queueConfig: {
        concurrency: 5,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "audio-mixing",
      label: "Audio Mixing",
      queueName: "audio-mixing",
      jobName: "mix-audio",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: true,
      configKey: "audioMixing",
      progressPercent: 70,
      projectStatus: "mixing_audio",
      sceneStatusOnComplete: "audio_mixed",
      dependsOn: ["tts-generation"],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "video-assembly",
      label: "Final Assembly",
      queueName: "video-assembly",
      jobName: "assemble-video",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "assembly",
      progressPercent: 85,
      projectStatus: "assembling",
      dependsOn: ["slide-rendering", "audio-mixing"],
      queueConfig: {
        concurrency: 2,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "ffmpeg",
    },
  ],
};
