import type { PipelineTemplate } from "../types/pipeline-template";

/**
 * Built-in Remotion pipeline template.
 * Creates videos using React components rendered via @remotion/renderer.
 */
export const REMOTION_TEMPLATE: PipelineTemplate = {
  id: "builtin-remotion",
  name: "Remotion Video",
  slug: "remotion",
  description:
    "Create videos using React components with Remotion. AI generates content and compositions, Remotion renders the final video.",
  version: 1,
  outputType: "remotion_video",
  isBuiltIn: true,
  createdBy: null,
  defaultConfig: {},
  stages: [
    {
      stageId: "ingestion",
      label: "Content Ingestion",
      queueName: "ingestion",
      jobName: "ingest",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "ingestion",
      progressPercent: 0,
      projectStatus: "ingesting",
      dependsOn: [],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "story-writing",
      label: "Story Writing",
      queueName: "story-writing",
      jobName: "write-story",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "storyWriting",
      progressPercent: 15,
      projectStatus: "writing",
      dependsOn: ["ingestion"],
      queueConfig: {
        concurrency: 3,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "scene-generation",
      label: "Scene Generation",
      queueName: "scene-generation",
      jobName: "generate-scenes",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "sceneGeneration",
      progressPercent: 30,
      projectStatus: "generating_scenes",
      dependsOn: ["story-writing"],
      queueConfig: {
        concurrency: 10,
        retries: 3,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
    },
    {
      stageId: "remotion-composition",
      label: "Remotion Composition",
      queueName: "remotion-composition",
      jobName: "create-composition",
      executionMode: "parallel-per-scene",
      completionStrategy: "all-scenes-done",
      canBeDisabled: false,
      configKey: "remotionComposition",
      progressPercent: 50,
      projectStatus: "generating_visuals",
      dependsOn: ["scene-generation"],
      queueConfig: {
        concurrency: 5,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 5000,
      },
      renderingBackend: "remotion",
    },
    {
      stageId: "remotion-render",
      label: "Remotion Render",
      queueName: "remotion-render",
      jobName: "render-remotion",
      executionMode: "sequential",
      canBeDisabled: false,
      configKey: "remotionRender",
      progressPercent: 75,
      projectStatus: "assembling",
      dependsOn: ["remotion-composition"],
      queueConfig: {
        concurrency: 2,
        retries: 2,
        backoffType: "exponential",
        backoffDelay: 10000,
      },
      renderingBackend: "remotion",
    },
  ],
};
